name: "Attio guMCP Server"
icon: "assets/icon.png"
description: "Server for interacting with Attio CRM data and records"
documentation_path: "README.md"
tools:
  - name: "search_companies"
    description: "Search for companies in Attio"
  - name: "read_company"
    description: "Read a specific company by ID"
  - name: "create_company"
    description: "Create a new company in Attio"
  - name: "update_company"
    description: "Update an existing company in Attio"
  - name: "search_contacts"
    description: "Search for contacts in Attio"
  - name: "read_contact"
    description: "Read a specific contact by ID"
  - name: "create_contact"
    description: "Create a new contact in Attio"
  - name: "update_contact"
    description: "Update an existing contact in Attio"
  - name: "list_lists"
    description: "List available lists in Attio"
  - name: "read_list"
    description: "Read a specific list by ID"
  - name: "add_to_list"
    description: "Add a record to a list in Attio"
